apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::573786860011:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-F8lVPLYIRd1t
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::573786860011:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-06T19:10:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1334"
  uid: db3066de-5143-48bb-8a51-f750ac01a940
